{{- if eq .Values.nginx.service.type "LoadBalancer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-ip-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-ip-reader-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-ip-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-ip-reader-role
subjects:
- kind: ServiceAccount
  name: external-ip-reader
{{- end }}