# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
name: push-dockerhub-on-demand

on:
  workflow_dispatch:
    inputs:
      dittoVersion:
        description: 'Ditto Image version'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2 # setup buildx in order to do build and push multi-architecture images
      -
        name: Inspect buildx builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eclipsedittobot
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Branch name
        id: branch_name
        run: |
          echo "IMAGE_TAG=${{ inputs.dittoVersion }}" >> $GITHUB_ENV
          echo "IMAGE_MINOR_TAG=$(echo ${{ inputs.dittoVersion }} | cut -d. -f-2)" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_TAG=$(echo ${{ inputs.dittoVersion }} | cut -d. -f-1)" >> $GITHUB_ENV
          echo "MILESTONE_OR_RC_SUFFIX=$(echo ${{ inputs.dittoVersion }} | cut -d- -f2)" >> $GITHUB_ENV
      -
        name: Building Docker images for tag
        run: |
          echo $IMAGE_TAG
          echo "Full version: $IMAGE_TAG"
          echo "Minor version: $IMAGE_MINOR_TAG"
          echo "Major version: $IMAGE_MAJOR_TAG"
          echo "Milestone or RC suffix: $MILESTONE_OR_RC_SUFFIX"
#      -
#        name: Build and push ditto-ui
#        if: env.MILESTONE_OR_RC_SUFFIX == env.IMAGE_TAG
#        uses: docker/build-push-action@v3
#        with:
#          context: ./ui
#          file: ui/Dockerfile
#          platforms: linux/amd64,linux/arm64
#          pull: true
#          push: true
#          tags: |
#            eclipse/ditto-ui:${{ env.IMAGE_TAG }}
#            eclipse/ditto-ui:${{ env.IMAGE_MINOR_TAG }}
#            eclipse/ditto-ui:${{ env.IMAGE_MAJOR_TAG }}
#            eclipse/ditto-ui:latest
